### ISSUE TITLE
Crash when pressed shareinfo.

### ISSUE THREAD

**Issue by alian2plus** [SerenaKit/Antoine#6]
Here is the log.
[https://pastebin.com/raw/uUEQZD3A ](CrashLog)

**Comment by NSAntoine** [comment]
Is this on an iPad?

**Comment by NSAntoine** [comment]
An iPhone XS Max, I see, hm idk why, will investigate later

**Comment by alian2plus** [comment]
Yes iPhone xsmax, and this didn't happen because of the last update, it happened since you have added it on the first place.
